### ISSUE TITLE
Problema na Execução

### ISSUE THREAD

**Issue by alissonandrade2020** [NaluFigueira/FastFeet#2]
OK, me ajuda ??? achei muito interessante o curso de fast, já até baixei, rsrs, só que não estou conseguindo rodar ele, resumindo colocar pra funcionar ! rsrs, me ajuda ??

Parabéns ficou top !

**Comment by alissonandrade2020** [comment]
FRONT OK

![image](https://user-images.githubusercontent.com/39311340/79173234-553c3c00-7dcd-11ea-9014-1628d6b78618.png)

**Comment by alissonandrade2020** [comment]
Eu fiz já A semana 11, 10, 9 e 8 da rocketseat, ai vi no seu linkedin o fastfeet, ai achei interessante, pode e ajudar  o front já tá OK, falta o backend e o mobile ???

**Comment by alissonandrade2020** [comment]
O mobile aparece isso ??

![image](https://user-images.githubusercontent.com/39311340/79173378-c11ea480-7dcd-11ea-89e8-1289bb7abc91.png)

**Comment by alissonandrade2020** [comment]
eu segui o passo a passo mas não tá indo :(

**Comment by NaluFigueira** [comment]
O mobile é pra aparecer isso mesmo, você está utilizando um dispositivo ou um emulador para executar?

**Comment by alissonandrade2020** [comment]
celular

**Comment by NaluFigueira** [comment]
Eu precisava de mais detalhes do erro, então, aquela é apenas a tela do node.

**Comment by alissonandrade2020** [comment]
O celular: mas agora tá assim: 
To reload the app press "r"
To open developer menu press "d"

**Comment by NaluFigueira** [comment]
Sim, está certo, qual seria o problema?

**Comment by alissonandrade2020** [comment]
vamos por parte: 

Crie um banco de dados no PostgreSQL e um contêiner redis com janela de encaixe.

Como faço isso ?

**Comment by NaluFigueira** [comment]
Você pode fazer isso de várias formas, é um pouco complicado explicar por aqui, mas você pode começar pelo docker.

**Comment by alissonandrade2020** [comment]
docker ???

**Comment by NaluFigueira** [comment]
https://www.docker.com/ <-- o docker funciona da mesma forma que um servidor, no git só disponibilizo o código e as migrations para alimentar a base. A base tem que ser criada localmente, pois não tenho acesso a um servidor para hospedar a api e banco.

**Comment by alissonandrade2020** [comment]
no caso eu baixo o docker desktop ??

**Comment by NaluFigueira** [comment]
Olha, eu vou fechar a issue, pois não se trata de um problema no projeto, mas qualquer dúvida desse tipo, por favor me chama no linkedin. Abra a issue apenas se for de fato um erro.
